CREATE DATABASE IF NOT EXISTS campus_trade_admin
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE campus_trade_admin;

DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS goods;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS colleges;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS admin_users;

CREATE TABLE admin_users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE colleges (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL UNIQUE,
  code VARCHAR(30) NOT NULL UNIQUE,
  student_count INT NOT NULL DEFAULT 0,
  goods_count INT NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT '启用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE students (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '学号',
  nickname VARCHAR(50) NOT NULL COMMENT '姓名',
  phone VARCHAR(20),
  college VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT '正常',
  goods_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  sort INT NOT NULL DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT '启用',
  goods_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE goods (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  category_id INT,
  category_name VARCHAR(50),
  price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  seller_id INT,
  seller_name VARCHAR(50),
  college VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT '待审核',
  views INT NOT NULL DEFAULT 0,
  description VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(50) NOT NULL UNIQUE,
  goods_id INT,
  goods_name VARCHAR(100),
  buyer_name VARCHAR(50),
  seller_name VARCHAR(50),
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT '待交易',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE reports (
  id INT PRIMARY KEY AUTO_INCREMENT,
  goods_id INT,
  goods_name VARCHAR(100),
  reporter_name VARCHAR(50),
  reason VARCHAR(500),
  status VARCHAR(20) NOT NULL DEFAULT '待处理',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
